
---
title: "Atrophy correlations"
author: "Rahat Hasan"
date: "May 10th, 2021"
output:   
  rmarkdown::html_document:
     theme: united
     highlight: tango
     code_folding: show
     toc: true
     toc_float: true
     df_print: paged
     smooth_scroll: true
     number_sections: false
     self_contained: true  
---
<style>
    body .main-container {
        max-width: 1600px;
    }
    
  caption {
    color: black;
    font-size: 1.5em;
  } 
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(ggpubr)
library(tidyverse)
```

# Code
```{r pressure, echo=TRUE, message=FALSE, warning=FALSE}
#Load the Mathys deconvolution results
load("../FTD_deconvolution/data/mathys_dtangle_res.RData")

#Get the QSBB IDs of the samples
qsbb_table <- 
    read_tsv("../data/UCL_samples.tsv") %>%
    dplyr::select(c("external_subject_id", "qsbb_id")) %>%
    distinct() %>%
    drop_na()

#Arrange the atrophy data
atrophy_data <- 
  read_excel("../data/FTD_Tammaryn_atrophy_scores_120219.xlsx") %>%
  dplyr::select("QSBB number", contains("Atrophy severity"), "Hemisphere frozen", "Most severe hemishpere") %>%
  dplyr::rename(qsbb_id=`QSBB number`) %>%
  dplyr::mutate_at(vars(contains("Atrophy severity")), as.factor) %>%
  dplyr::mutate(atrophy_balance=ifelse(`Most severe hemishpere`==`Hemisphere frozen`, "more_severe",
                                ifelse(`Most severe hemishpere` == 'symmetrical', "symmetrical", 
                                       ifelse(`Most severe hemishpere` == "na", "NA", "less_severe")))) %>%
  dplyr::mutate(atrophy_balance = as.factor(atrophy_balance)) %>%
  pivot_longer(cols=contains("Atrophy severity"), names_to="atrophy_type", values_to="atrophy_score") %>%
  dplyr::mutate(tissue = ifelse(grepl("frontal", atrophy_type), "Frontal_Cortex", "Temporal_Cortex"),
         atrophy_type = ifelse(grepl("macro", atrophy_type), "Macrostructural", "Microstructural")) 

#Arrange the deconvolution data  
deconv_data <- 
  mathys_dtangle_res %>%
  dplyr::select("individual", "sample", "cell", "tissue", "disease", "deconv") %>%
  dplyr::rename(external_subject_id=individual) 
 
#For each sample, combine the atrophy data with the deconvolution data 
combined_data <- 
  left_join(deconv_data, qsbb_table, by="external_subject_id") %>%
  left_join(atrophy_data, by=c("qsbb_id", "tissue")) %>% drop_na(atrophy_score) %>%
  filter(tissue != "Cerebellum")

combined_data$cell <- factor(combined_data$cell , levels=c("End", "Per", "Ast", "Oli", "Mic", "Ex", "In"))

levels(combined_data$cell) <- c("Endothelial", "Pericytes", "Astrocytes", "Oligos", "Microglia", "Excitatory\nneurons", "Inhibitory\nneurons")
```

# Microscopic atrophy
```{r echo=TRUE, fig.height=6, fig.width=10, message=FALSE, warning=FALSE}
combined_data %>% 
  filter(atrophy_type=="Microstructural" & atrophy_score != "na") %>%
  mutate(atrophy_score=as.factor(atrophy_score)) %>%
  ggplot(aes(x=atrophy_score, y=deconv, group=atrophy_score))+
    geom_jitter(width=0.25, size=1, color="gray55", aes(shape=as.factor(atrophy_balance)))+
    geom_boxplot(lwd=0.3, outlier.colour=NA, fill=NA, color="black")+
    scale_shape_manual(name="Atrophy balance", values=c(17, 15, 4, 19))+
    scale_x_discrete(labels=c("1", "2", "3"))+
    scale_y_continuous(labels = scales::percent_format(accuracy = 1))+
    stat_compare_means(label="p.signif", comparisons=list(c("0", "1"), c("1","2")),  hide.ns=FALSE, label.y.npc=0.7, size=2.5)+
    facet_wrap(tissue~cell, scales="free", ncol=7)+ 
    labs(title="Microscopic atrophy", x = "Atrophy severity score", y = "Estimated proportion from Mathys")+
    theme_bw(base_size=9)+
      theme(
      legend.position="top",
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      panel.border = element_blank(),
      axis.line = element_line(color="black"),
      strip.background = element_blank(),
      panel.spacing = unit(0.5, "lines"))


```

# Macroscopic atrophy
```{r echo=TRUE, fig.height=6, fig.width=10, message=FALSE, warning=FALSE}
combined_data %>% 
  filter(atrophy_type=="Macrostructural") %>%
  mutate(atrophy_score=as.factor(atrophy_score)) %>%
  ggplot(aes(x=atrophy_score, y=deconv, group=atrophy_score))+
    geom_jitter(width=0.25, size=1, color="gray55", aes(shape=as.factor(atrophy_balance)))+
    geom_boxplot(lwd=0.3, outlier.colour=NA, fill=NA, color="black")+
    scale_shape_manual(name="Atrophy balance", values=c(17, 15, 4, 19))+
    scale_x_discrete(labels=c("0", "1", "2", "3"))+
    scale_y_continuous(labels = scales::percent_format(accuracy = 1))+
    stat_compare_means(label="p.signif", comparisons=list(c("0", "1"), c("1","2"), c("2", "3")),  hide.ns=FALSE, label.y.npc=0.7, size=2.5)+
    facet_wrap(tissue~cell, scales="free", ncol=7)+ 
    labs(title="Macroscopic atrophy", x = "Atrophy severity score", y = "Estimated proportion from Mathys")+
      theme_bw(base_size=9)+
      theme(
      legend.position="top",
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      panel.border = element_blank(),
      axis.line = element_line(color="black"),
      strip.background = element_blank(),
      panel.spacing = unit(0.5, "lines"))

```


