
---
title: "Deconvolution plots"
subtitle: "Darmanis and Mathys single cell"
author: "Rahat Hasan"
date: "February 18, 2021"
output:   
  rmarkdown::html_document:
     theme: united
     highlight: tango
     code_folding: show
     toc: true
     toc_float: true
     df_print: paged
     smooth_scroll: true
     number_sections: false
     self_contained: true  
---
<style>
    body .main-container {
        max-width: 1600px;
    }
    
  caption {
    color: black;
    font-size: 1.5em;
  } 
</style>

```{r load.packages, message=FALSE, include=FALSE, results='hide'}

if(!require("knitr")) install.packages("knitr", repos = c('http://rforge.net', 'http://cran.rstudio.org')); library("knitr")
if(!require("tidyverse")) install.packages("tidyverse"); library(tidyverse)
if(!require("readxl")) install.packages("readxl"); library(readxl)
if(!require("reshape2")) install.packages("reshape2"); library(reshape2)
if(!require("ggsci")) install.packages("ggsci"); library(ggsci)
if(!require("ggpubr")) install.packages("ggpubr");library(ggpubr)
if(!require("egg")) install.packages("egg");library(egg)
library("patchwork")


```


# Code
```{r echo=TRUE, message=FALSE, warning=FALSE}
#Function for plotting the deconvolution results
deconv_plotter <- function(deconv_data, title, subtitle){
  
    fc_plot <-
      filter(deconv_data, tissue=="Frontal_Cortex") %>%
      ggplot(aes(x = disease, y = deconv)) +
      geom_jitter(aes(color=disease), width=0.25)+
      geom_boxplot(color="black", lwd=0.3, fill=NA, notch = F, na.rm = TRUE, outlier.color = NA) +
      facet_wrap(~cell, scales="free", ncol=7) +
      ggpubr::stat_compare_means(label="p.signif", label.x.npc=0.5, label.y.npc=0.86, hide.ns=FALSE)+
      scale_y_continuous(labels = scales::percent_format(accuracy = 1))+
      scale_color_manual(labels=c("Control", "FTLD-TDP"), values=c("dodgerblue", "orange"))+
      xlab(NULL)+ylab(NULL)+
      ggtitle(label=title, subtitle=subtitle)+
      scale_x_discrete(name="Disease")+
      theme_bw()+ 
      theme(
        legend.position="top",
        legend.title=element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_blank(),
        strip.background = element_blank(),
        axis.line = element_line(color="black"),
        axis.title = element_blank())
  

  tc_plot <-
    filter(deconv_data, tissue=="Temporal_Cortex") %>%
    ggplot(aes(x = disease, y = deconv, group=disease)) +
    geom_jitter(aes(color=disease), width=0.25, show.legend=FALSE)+
    geom_boxplot(color="black", lwd=0.3, fill=NA, notch = F, outlier.color = NA, show.legend=FALSE) +
    facet_wrap(~cell, scales="free", ncol=7) +
    ggpubr::stat_compare_means(label="p.signif", label.x.npc=0.5, label.y.npc=0.86, hide.ns=FALSE)+
    scale_y_continuous(labels = scales::percent_format(accuracy = 1))+
    scale_color_manual(values=c("dodgerblue", "orange"))+
    xlab(NULL)+ylab("Estimated proportion")+
    labs(color="Disease")+
    theme_bw(base_size=9)+ 
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      panel.border = element_blank(),
      strip.background = element_blank(),
      strip.text = element_blank(),
      axis.line = element_line(color="black"))
  
  cb_plot <-
    filter(deconv_data, tissue=="Cerebellum") %>%
    ggplot(aes(x = disease, y = deconv, group=disease)) +
    geom_jitter(aes(color=disease), width=0.25, show.legend=FALSE)+
    geom_boxplot(color="black", lwd=0.3, fill=NA, notch = F, outlier.color = NA, show.legend=FALSE) +
    facet_wrap(~cell, scales="free", ncol=7) +
    ggpubr::stat_compare_means(label="p.signif", label.x.npc=0.5, label.y.npc=0.86, hide.ns=FALSE)+
    scale_y_continuous(labels = scales::percent_format(accuracy = 1))+
    scale_color_manual(values=c("dodgerblue", "orange"))+
    scale_x_discrete(labels=c("Control", "FTLD-TDP"))+
    xlab(NULL)+ylab(NULL)+
    labs(color="Disease")+
    theme_bw(base_size=9)+ 
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      panel.border = element_blank(),
      strip.background = element_blank(),
      strip.text = element_blank(),
      axis.line = element_line(color="black"))

 deconv_plots <- fc_plot+tc_plot+cb_plot+plot_layout(nrow=3)
 print(deconv_plots)
}


```

# Deconvolution estimates {.tabset .tabset-fade .tabset-pills}

## dtangle {.tabset .tabset-fade .tabset-pills}

```{r echo=TRUE, fig.height=8, fig.width=14, message=FALSE, warning=FALSE}
#Load the results
load("data/darmanis_dtangle_res.RData")
load("data/mathys_dtangle_res.RData")

deconv_plotter(darmanis_dtangle_res, title="Darmanis single cell", subtitle="dtangle")
deconv_plotter(mathys_dtangle_res, title="Mathys single cell", subtitle="dtangle")

```

## MuSiC {.tabset .tabset-fade .tabset-pills}

```{r echo=TRUE, fig.height=8, fig.width=14, message=FALSE, warning=FALSE, ,echo=FALSE, messsage=FALSE, res=300}
load("data/darmanis_music_res.RData")

deconv_plotter(darmanis_music_res, title="Darmanis single cell", subtitle="MuSiC")
```


# Correlations between references

```{r echo=TRUE, fig.height=8, fig.width=11, message=FALSE, warning=FALSE}
#For pairs of results, calculate correlation between the estimate of neuronal, endothelial, astrocyte, oligodendrocyte, and microglial proportion in each sample

darmanis_dtangle_renamed <- dplyr::rename(darmanis_dtangle_res, darmanis_deconv=deconv)

mathys_dtangle_renamed <- 
  dplyr::rename(mathys_dtangle_res, mathys_deconv=deconv) %>% 
  mutate(cell = ifelse(cell=="End", "endothelial", 
                       ifelse(cell=="Ast", "astrocytes",
                              ifelse(cell=="Oli", "oligodendrocytes",
                                     ifelse(cell=="Mic", "microglia", cell)))))

combined_deconv_data <-
  darmanis_dtangle_renamed %>%
  left_join(dplyr::select(mathys_dtangle_renamed, c("sample", "cell", "mathys_deconv")), by=c("sample", "cell")) 

combined_deconv_data$tissue <- factor(combined_deconv_data$tissue, levels=c("Frontal_Cortex", "Temporal_Cortex", "Cerebellum"))
combined_deconv_data$cell <- factor(combined_deconv_data$cell, levels=c("endothelial", "astrocytes", "microglia", "oligodendrocytes"))

combined_deconv_data %>%
  filter(cell %in% c("endothelial", "astrocytes", "oligodendrocytes", "microglia")) %>%
  ggplot(aes(x=mathys_deconv, y=darmanis_deconv))+
  geom_point(aes(color=disease))+
  geom_smooth(method="lm", se=FALSE, color="black", linetype="dotted")+
  stat_cor(method="pearson", aes(label = ..r.label..), size=3)+
  facet_wrap(tissue~cell, scales="free_x")+
  theme_bw()+ 
  ggtitle("Mathys vs Darmanis single cell", subtitle="dtangle")+
  xlab("dtangle estimates with Mathys")+
  ylab("dtangle estimates with Darmanis")+
  scale_x_continuous(labels = scales::percent_format(accuracy = 1))+
  scale_y_continuous(labels = scales::percent_format(accuracy = 1))+
  scale_color_manual(labels=c("Control", "FTLD-TDP"), values=c("dodgerblue", "orange"))+
  theme(
    legend.position="top",
    legend.title=element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    panel.border = element_blank(),
    strip.background = element_blank(),
    axis.line = element_line(colour = "black"))
  
```

# Correlations between methods
```{r echo=TRUE, fig.height=8, fig.width=11, message=FALSE, warning=FALSE}
#Calculate correlation between dtangle and MuSiC reults, using darmanis reference
darmanis_dtangle_renamed <- dplyr::rename(darmanis_dtangle_res, dtangle_deconv=deconv)
darmanis_music_renamed <- dplyr::rename(darmanis_music_res, music_deconv=deconv)

combined_deconv_data <-
  darmanis_dtangle_renamed %>%
  left_join(dplyr::select(darmanis_music_renamed, c("sample", "cell", "music_deconv")), by=c("sample", "cell")) 

combined_deconv_data$tissue <- factor(combined_deconv_data$tissue, levels=c("Frontal_Cortex", "Temporal_Cortex", "Cerebellum"))
combined_deconv_data$cell <- factor(combined_deconv_data$cell, levels=c("endothelial", "astrocytes", "microglia", "oligodendrocytes", "neurons"))

combined_deconv_data %>%
  ggplot(aes(x=dtangle_deconv, y=music_deconv))+
  geom_point(aes(color=disease))+
  geom_smooth(method="lm", se=FALSE, color="black", linetype="dotted")+
  stat_cor(method="pearson", aes(label = ..r.label..), size=3)+
  facet_wrap(tissue~cell, scales="free_x", ncol=5)+
  theme_bw()+ 
  ggtitle("dtangle vs MuSiC", subtitle="Darmanis single cell")+
  xlab("dtangle estimates")+
  ylab("MuSiC estimates")+
  scale_x_continuous(labels = scales::percent_format(accuracy = 1))+
  scale_y_continuous(labels = scales::percent_format(accuracy = 1))+
  scale_color_manual(labels=c("Control", "FTLD-TDP"), values=c("dodgerblue", "orange"))+
  theme(
    legend.position="top",
    legend.title=element_blank(),
    legend.text=element_text(size=7),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    panel.border = element_blank(),
    axis.line = element_line(colour = "black"),
    strip.background = element_blank())


```




